# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(e8515213-fc4a-411b-a304-e14a787e7f0f)'
    appType: 'webAppLinux'
    appName: 'msdocs-python-webapp-quickstart-678'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
  displayName: 'dotnet build $(buildConfiguration)'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(1)(e8515213-fc4a-411b-a304-e14a787e7f0f)'
    appType: 'webAppLinux'
    appName: 'msdocs-python-webapp-quickstart-678'
    deployToSlotOrASE: true
    resourceGroupName: 'msdocs-python-webapp-quickstart'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'PYTHON|3.9'